version: "3.8"
services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000" 
    image: visheshvishu/wanderlust_backend:latest
    depends_on: 
      - redis
      - mongodb  

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    depends_on:
      - backend
    ports:
      - "5173:5173"
    image: visheshvishu/wanderlust_frontend:latest

  mongodb:
    container_name: mongo
    image: mongo:latest  
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:latest    
    ports:
      - "6379:6379"    

volumes:
  data:
