# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: wanderlust
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: mongo-storage
              mountPath: /var/lib/redis/dump.rdb
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
# redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: wanderlust
spec:
  selector:
    app: redis
  ports:
    - port: 6379
