# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlust
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: visheshvishu/wanderlust_backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/wanderlust"
            - name: REDIS_URL
              value: "redis://redis:6379"

---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wanderlust
spec:
  selector:
    app: backend
  ports:
    - port: 5000
